// Code generated by protoc-gen-go. DO NOT EDIT.
// source: activity.proto

package activitypb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ReqRequest struct {
	Url                  string               `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Req                  []byte               `protobuf:"bytes,2,opt,name=req,proto3" json:"req,omitempty"`
	Completed            bool                 `protobuf:"varint,3,opt,name=completed,proto3" json:"completed,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ReqRequest) Reset()         { *m = ReqRequest{} }
func (m *ReqRequest) String() string { return proto.CompactTextString(m) }
func (*ReqRequest) ProtoMessage()    {}
func (*ReqRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_activity_284b00025e5c3ca5, []int{0}
}
func (m *ReqRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqRequest.Unmarshal(m, b)
}
func (m *ReqRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqRequest.Marshal(b, m, deterministic)
}
func (dst *ReqRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqRequest.Merge(dst, src)
}
func (m *ReqRequest) XXX_Size() int {
	return xxx_messageInfo_ReqRequest.Size(m)
}
func (m *ReqRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReqRequest proto.InternalMessageInfo

func (m *ReqRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *ReqRequest) GetReq() []byte {
	if m != nil {
		return m.Req
	}
	return nil
}

func (m *ReqRequest) GetCompleted() bool {
	if m != nil {
		return m.Completed
	}
	return false
}

func (m *ReqRequest) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *ReqRequest) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type ReqReply struct {
	ReqId                int32    `protobuf:"varint,1,opt,name=reqId,proto3" json:"reqId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqReply) Reset()         { *m = ReqReply{} }
func (m *ReqReply) String() string { return proto.CompactTextString(m) }
func (*ReqReply) ProtoMessage()    {}
func (*ReqReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_activity_284b00025e5c3ca5, []int{1}
}
func (m *ReqReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqReply.Unmarshal(m, b)
}
func (m *ReqReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqReply.Marshal(b, m, deterministic)
}
func (dst *ReqReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqReply.Merge(dst, src)
}
func (m *ReqReply) XXX_Size() int {
	return xxx_messageInfo_ReqReply.Size(m)
}
func (m *ReqReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqReply.DiscardUnknown(m)
}

var xxx_messageInfo_ReqReply proto.InternalMessageInfo

func (m *ReqReply) GetReqId() int32 {
	if m != nil {
		return m.ReqId
	}
	return 0
}

type ResRequest struct {
	ReqId                int32                `protobuf:"varint,1,opt,name=reqId,proto3" json:"reqId,omitempty"`
	Response             []byte               `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ResRequest) Reset()         { *m = ResRequest{} }
func (m *ResRequest) String() string { return proto.CompactTextString(m) }
func (*ResRequest) ProtoMessage()    {}
func (*ResRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_activity_284b00025e5c3ca5, []int{2}
}
func (m *ResRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResRequest.Unmarshal(m, b)
}
func (m *ResRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResRequest.Marshal(b, m, deterministic)
}
func (dst *ResRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResRequest.Merge(dst, src)
}
func (m *ResRequest) XXX_Size() int {
	return xxx_messageInfo_ResRequest.Size(m)
}
func (m *ResRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResRequest proto.InternalMessageInfo

func (m *ResRequest) GetReqId() int32 {
	if m != nil {
		return m.ReqId
	}
	return 0
}

func (m *ResRequest) GetResponse() []byte {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *ResRequest) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type ResReply struct {
	ResId                int32    `protobuf:"varint,1,opt,name=resId,proto3" json:"resId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResReply) Reset()         { *m = ResReply{} }
func (m *ResReply) String() string { return proto.CompactTextString(m) }
func (*ResReply) ProtoMessage()    {}
func (*ResReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_activity_284b00025e5c3ca5, []int{3}
}
func (m *ResReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResReply.Unmarshal(m, b)
}
func (m *ResReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResReply.Marshal(b, m, deterministic)
}
func (dst *ResReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResReply.Merge(dst, src)
}
func (m *ResReply) XXX_Size() int {
	return xxx_messageInfo_ResReply.Size(m)
}
func (m *ResReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ResReply.DiscardUnknown(m)
}

var xxx_messageInfo_ResReply proto.InternalMessageInfo

func (m *ResReply) GetResId() int32 {
	if m != nil {
		return m.ResId
	}
	return 0
}

func init() {
	proto.RegisterType((*ReqRequest)(nil), "activitypb.ReqRequest")
	proto.RegisterType((*ReqReply)(nil), "activitypb.ReqReply")
	proto.RegisterType((*ResRequest)(nil), "activitypb.ResRequest")
	proto.RegisterType((*ResReply)(nil), "activitypb.ResReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ActivityClient is the client API for Activity service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ActivityClient interface {
	StoreRequest(ctx context.Context, in *ReqRequest, opts ...grpc.CallOption) (*ReqReply, error)
	UpdateReqReply(ctx context.Context, in *ReqRequest, opts ...grpc.CallOption) (*ReqReply, error)
	StoreResponse(ctx context.Context, in *ResRequest, opts ...grpc.CallOption) (*ResReply, error)
}

type activityClient struct {
	cc *grpc.ClientConn
}

func NewActivityClient(cc *grpc.ClientConn) ActivityClient {
	return &activityClient{cc}
}

func (c *activityClient) StoreRequest(ctx context.Context, in *ReqRequest, opts ...grpc.CallOption) (*ReqReply, error) {
	out := new(ReqReply)
	err := c.cc.Invoke(ctx, "/activitypb.Activity/StoreRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityClient) UpdateReqReply(ctx context.Context, in *ReqRequest, opts ...grpc.CallOption) (*ReqReply, error) {
	out := new(ReqReply)
	err := c.cc.Invoke(ctx, "/activitypb.Activity/UpdateReqReply", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityClient) StoreResponse(ctx context.Context, in *ResRequest, opts ...grpc.CallOption) (*ResReply, error) {
	out := new(ResReply)
	err := c.cc.Invoke(ctx, "/activitypb.Activity/StoreResponse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ActivityServer is the server API for Activity service.
type ActivityServer interface {
	StoreRequest(context.Context, *ReqRequest) (*ReqReply, error)
	UpdateReqReply(context.Context, *ReqRequest) (*ReqReply, error)
	StoreResponse(context.Context, *ResRequest) (*ResReply, error)
}

func RegisterActivityServer(s *grpc.Server, srv ActivityServer) {
	s.RegisterService(&_Activity_serviceDesc, srv)
}

func _Activity_StoreRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServer).StoreRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/activitypb.Activity/StoreRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServer).StoreRequest(ctx, req.(*ReqRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Activity_UpdateReqReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServer).UpdateReqReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/activitypb.Activity/UpdateReqReply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServer).UpdateReqReply(ctx, req.(*ReqRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Activity_StoreResponse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServer).StoreResponse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/activitypb.Activity/StoreResponse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServer).StoreResponse(ctx, req.(*ResRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Activity_serviceDesc = grpc.ServiceDesc{
	ServiceName: "activitypb.Activity",
	HandlerType: (*ActivityServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StoreRequest",
			Handler:    _Activity_StoreRequest_Handler,
		},
		{
			MethodName: "UpdateReqReply",
			Handler:    _Activity_UpdateReqReply_Handler,
		},
		{
			MethodName: "StoreResponse",
			Handler:    _Activity_StoreResponse_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "activity.proto",
}

func init() { proto.RegisterFile("activity.proto", fileDescriptor_activity_284b00025e5c3ca5) }

var fileDescriptor_activity_284b00025e5c3ca5 = []byte{
	// 319 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x3d, 0x4f, 0xf3, 0x30,
	0x10, 0xc7, 0x1f, 0x3f, 0xa5, 0x28, 0x3d, 0x4a, 0x85, 0xac, 0x0a, 0x45, 0x11, 0x12, 0x51, 0xa6,
	0x4c, 0xae, 0x54, 0x16, 0x26, 0xa0, 0x6c, 0x5d, 0x0d, 0x2c, 0x6c, 0x6d, 0x72, 0x54, 0x91, 0x12,
	0xec, 0xd8, 0x0e, 0x22, 0x5f, 0x8f, 0x9d, 0xef, 0x84, 0x92, 0x38, 0x2f, 0xbc, 0x09, 0x75, 0xbb,
	0xbb, 0xdc, 0xfd, 0xf3, 0xff, 0xdd, 0x19, 0x66, 0x9b, 0xc8, 0x24, 0x2f, 0x89, 0x29, 0x99, 0x54,
	0xc2, 0x08, 0x0a, 0x6d, 0x2e, 0xb7, 0xde, 0xf9, 0x4e, 0x88, 0x5d, 0x8a, 0x8b, 0xfa, 0xcb, 0xb6,
	0x78, 0x5a, 0x98, 0x24, 0x43, 0x6d, 0x36, 0x99, 0x6c, 0x9a, 0x83, 0x37, 0x02, 0xc0, 0x31, 0xe7,
	0x98, 0x17, 0xa8, 0x0d, 0x3d, 0x81, 0x51, 0xa1, 0x52, 0x97, 0xf8, 0x24, 0x9c, 0xf0, 0x2a, 0xac,
	0x2a, 0x0a, 0x73, 0xf7, 0xbf, 0x4f, 0xc2, 0x29, 0xaf, 0x42, 0x7a, 0x06, 0x93, 0x48, 0x64, 0x32,
	0x45, 0x83, 0xb1, 0x3b, 0xf2, 0x49, 0xe8, 0xf0, 0xbe, 0x40, 0x2f, 0x61, 0x12, 0x29, 0xdc, 0x18,
	0x8c, 0x57, 0xc6, 0x3d, 0xf0, 0x49, 0x78, 0xb4, 0xf4, 0x58, 0xe3, 0x82, 0xb5, 0x2e, 0xd8, 0x7d,
	0xeb, 0x82, 0xf7, 0xcd, 0xd5, 0x64, 0x21, 0x63, 0x3b, 0x39, 0xfe, 0x7b, 0xb2, 0x6b, 0x0e, 0x7c,
	0x70, 0x6a, 0x06, 0x99, 0x96, 0x74, 0x0e, 0x63, 0x85, 0xf9, 0x3a, 0xae, 0x19, 0xc6, 0xbc, 0x49,
	0x82, 0xd7, 0x8a, 0x52, 0xb7, 0x94, 0x3f, 0xf6, 0x50, 0x0f, 0x1c, 0x85, 0x5a, 0x8a, 0x67, 0x8d,
	0x16, 0xb7, 0xcb, 0x3f, 0x53, 0x8d, 0xf6, 0xa0, 0x6a, 0xbc, 0xe9, 0x81, 0x37, 0x3d, 0xfc, 0xaf,
	0x5e, 0xc7, 0xcb, 0x77, 0x02, 0xce, 0xca, 0x9e, 0x8c, 0x5e, 0xc1, 0xf4, 0xce, 0x08, 0x85, 0xad,
	0xd5, 0x53, 0xd6, 0x5f, 0x93, 0xf5, 0x87, 0xf2, 0xe6, 0xdf, 0xea, 0x32, 0x2d, 0x83, 0x7f, 0xf4,
	0x06, 0x66, 0x0f, 0xf5, 0x5e, 0xba, 0x85, 0xec, 0xab, 0x70, 0x0d, 0xc7, 0xd6, 0x81, 0x65, 0xff,
	0x22, 0xa0, 0x7f, 0x11, 0xd0, 0x56, 0xe0, 0x76, 0xfa, 0x38, 0x78, 0x81, 0xdb, 0xc3, 0x7a, 0x3d,
	0x17, 0x1f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x7a, 0x80, 0x65, 0xeb, 0xa6, 0x02, 0x00, 0x00,
}
