// Code generated by protoc-gen-go. DO NOT EDIT.
// source: activity.proto

package activitypb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ReqRequest struct {
	ReqId                int32    `protobuf:"varint,1,opt,name=reqId,proto3" json:"reqId,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Header               []byte   `protobuf:"bytes,3,opt,name=header,proto3" json:"header,omitempty"`
	Completed            bool     `protobuf:"varint,4,opt,name=completed,proto3" json:"completed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqRequest) Reset()         { *m = ReqRequest{} }
func (m *ReqRequest) String() string { return proto.CompactTextString(m) }
func (*ReqRequest) ProtoMessage()    {}
func (*ReqRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_activity_569024038f4898c5, []int{0}
}
func (m *ReqRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqRequest.Unmarshal(m, b)
}
func (m *ReqRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqRequest.Marshal(b, m, deterministic)
}
func (dst *ReqRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqRequest.Merge(dst, src)
}
func (m *ReqRequest) XXX_Size() int {
	return xxx_messageInfo_ReqRequest.Size(m)
}
func (m *ReqRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReqRequest proto.InternalMessageInfo

func (m *ReqRequest) GetReqId() int32 {
	if m != nil {
		return m.ReqId
	}
	return 0
}

func (m *ReqRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *ReqRequest) GetHeader() []byte {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ReqRequest) GetCompleted() bool {
	if m != nil {
		return m.Completed
	}
	return false
}

type ReqReply struct {
	ReqId                int32    `protobuf:"varint,1,opt,name=reqId,proto3" json:"reqId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqReply) Reset()         { *m = ReqReply{} }
func (m *ReqReply) String() string { return proto.CompactTextString(m) }
func (*ReqReply) ProtoMessage()    {}
func (*ReqReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_activity_569024038f4898c5, []int{1}
}
func (m *ReqReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqReply.Unmarshal(m, b)
}
func (m *ReqReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqReply.Marshal(b, m, deterministic)
}
func (dst *ReqReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqReply.Merge(dst, src)
}
func (m *ReqReply) XXX_Size() int {
	return xxx_messageInfo_ReqReply.Size(m)
}
func (m *ReqReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqReply.DiscardUnknown(m)
}

var xxx_messageInfo_ReqReply proto.InternalMessageInfo

func (m *ReqReply) GetReqId() int32 {
	if m != nil {
		return m.ReqId
	}
	return 0
}

type GetRequestsReply struct {
	Requests             []*ReqRequest `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetRequestsReply) Reset()         { *m = GetRequestsReply{} }
func (m *GetRequestsReply) String() string { return proto.CompactTextString(m) }
func (*GetRequestsReply) ProtoMessage()    {}
func (*GetRequestsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_activity_569024038f4898c5, []int{2}
}
func (m *GetRequestsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequestsReply.Unmarshal(m, b)
}
func (m *GetRequestsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequestsReply.Marshal(b, m, deterministic)
}
func (dst *GetRequestsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequestsReply.Merge(dst, src)
}
func (m *GetRequestsReply) XXX_Size() int {
	return xxx_messageInfo_GetRequestsReply.Size(m)
}
func (m *GetRequestsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequestsReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequestsReply proto.InternalMessageInfo

func (m *GetRequestsReply) GetRequests() []*ReqRequest {
	if m != nil {
		return m.Requests
	}
	return nil
}

type ResRequest struct {
	Host                 string               `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Url                  string               `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Response             []byte               `protobuf:"bytes,3,opt,name=response,proto3" json:"response,omitempty"`
	Body                 []byte               `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Expires              *timestamp.Timestamp `protobuf:"bytes,5,opt,name=expires,proto3" json:"expires,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ResRequest) Reset()         { *m = ResRequest{} }
func (m *ResRequest) String() string { return proto.CompactTextString(m) }
func (*ResRequest) ProtoMessage()    {}
func (*ResRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_activity_569024038f4898c5, []int{3}
}
func (m *ResRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResRequest.Unmarshal(m, b)
}
func (m *ResRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResRequest.Marshal(b, m, deterministic)
}
func (dst *ResRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResRequest.Merge(dst, src)
}
func (m *ResRequest) XXX_Size() int {
	return xxx_messageInfo_ResRequest.Size(m)
}
func (m *ResRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResRequest proto.InternalMessageInfo

func (m *ResRequest) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *ResRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *ResRequest) GetResponse() []byte {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *ResRequest) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *ResRequest) GetExpires() *timestamp.Timestamp {
	if m != nil {
		return m.Expires
	}
	return nil
}

type GetResRequest struct {
	Host                 string   `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResRequest) Reset()         { *m = GetResRequest{} }
func (m *GetResRequest) String() string { return proto.CompactTextString(m) }
func (*GetResRequest) ProtoMessage()    {}
func (*GetResRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_activity_569024038f4898c5, []int{4}
}
func (m *GetResRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResRequest.Unmarshal(m, b)
}
func (m *GetResRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResRequest.Marshal(b, m, deterministic)
}
func (dst *GetResRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResRequest.Merge(dst, src)
}
func (m *GetResRequest) XXX_Size() int {
	return xxx_messageInfo_GetResRequest.Size(m)
}
func (m *GetResRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetResRequest proto.InternalMessageInfo

func (m *GetResRequest) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *GetResRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type HostSizeRequest struct {
	Host                 string   `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HostSizeRequest) Reset()         { *m = HostSizeRequest{} }
func (m *HostSizeRequest) String() string { return proto.CompactTextString(m) }
func (*HostSizeRequest) ProtoMessage()    {}
func (*HostSizeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_activity_569024038f4898c5, []int{5}
}
func (m *HostSizeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HostSizeRequest.Unmarshal(m, b)
}
func (m *HostSizeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HostSizeRequest.Marshal(b, m, deterministic)
}
func (dst *HostSizeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HostSizeRequest.Merge(dst, src)
}
func (m *HostSizeRequest) XXX_Size() int {
	return xxx_messageInfo_HostSizeRequest.Size(m)
}
func (m *HostSizeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HostSizeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HostSizeRequest proto.InternalMessageInfo

func (m *HostSizeRequest) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

type HostSizeReply struct {
	Size                 int64    `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HostSizeReply) Reset()         { *m = HostSizeReply{} }
func (m *HostSizeReply) String() string { return proto.CompactTextString(m) }
func (*HostSizeReply) ProtoMessage()    {}
func (*HostSizeReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_activity_569024038f4898c5, []int{6}
}
func (m *HostSizeReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HostSizeReply.Unmarshal(m, b)
}
func (m *HostSizeReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HostSizeReply.Marshal(b, m, deterministic)
}
func (dst *HostSizeReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HostSizeReply.Merge(dst, src)
}
func (m *HostSizeReply) XXX_Size() int {
	return xxx_messageInfo_HostSizeReply.Size(m)
}
func (m *HostSizeReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HostSizeReply.DiscardUnknown(m)
}

var xxx_messageInfo_HostSizeReply proto.InternalMessageInfo

func (m *HostSizeReply) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func init() {
	proto.RegisterType((*ReqRequest)(nil), "activitypb.ReqRequest")
	proto.RegisterType((*ReqReply)(nil), "activitypb.ReqReply")
	proto.RegisterType((*GetRequestsReply)(nil), "activitypb.GetRequestsReply")
	proto.RegisterType((*ResRequest)(nil), "activitypb.ResRequest")
	proto.RegisterType((*GetResRequest)(nil), "activitypb.GetResRequest")
	proto.RegisterType((*HostSizeRequest)(nil), "activitypb.HostSizeRequest")
	proto.RegisterType((*HostSizeReply)(nil), "activitypb.HostSizeReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ActivityClient is the client API for Activity service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ActivityClient interface {
	StoreRequest(ctx context.Context, in *ReqRequest, opts ...grpc.CallOption) (*ReqReply, error)
	GetRequests(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetRequestsReply, error)
	UpdateRequest(ctx context.Context, in *ReqRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	StoreResponse(ctx context.Context, in *ResRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	GetResponse(ctx context.Context, in *GetResRequest, opts ...grpc.CallOption) (*ResRequest, error)
	GetHostSize(ctx context.Context, in *HostSizeRequest, opts ...grpc.CallOption) (*HostSizeReply, error)
}

type activityClient struct {
	cc *grpc.ClientConn
}

func NewActivityClient(cc *grpc.ClientConn) ActivityClient {
	return &activityClient{cc}
}

func (c *activityClient) StoreRequest(ctx context.Context, in *ReqRequest, opts ...grpc.CallOption) (*ReqReply, error) {
	out := new(ReqReply)
	err := c.cc.Invoke(ctx, "/activitypb.Activity/StoreRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityClient) GetRequests(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetRequestsReply, error) {
	out := new(GetRequestsReply)
	err := c.cc.Invoke(ctx, "/activitypb.Activity/GetRequests", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityClient) UpdateRequest(ctx context.Context, in *ReqRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/activitypb.Activity/UpdateRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityClient) StoreResponse(ctx context.Context, in *ResRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/activitypb.Activity/StoreResponse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityClient) GetResponse(ctx context.Context, in *GetResRequest, opts ...grpc.CallOption) (*ResRequest, error) {
	out := new(ResRequest)
	err := c.cc.Invoke(ctx, "/activitypb.Activity/GetResponse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityClient) GetHostSize(ctx context.Context, in *HostSizeRequest, opts ...grpc.CallOption) (*HostSizeReply, error) {
	out := new(HostSizeReply)
	err := c.cc.Invoke(ctx, "/activitypb.Activity/GetHostSize", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ActivityServer is the server API for Activity service.
type ActivityServer interface {
	StoreRequest(context.Context, *ReqRequest) (*ReqReply, error)
	GetRequests(context.Context, *empty.Empty) (*GetRequestsReply, error)
	UpdateRequest(context.Context, *ReqRequest) (*empty.Empty, error)
	StoreResponse(context.Context, *ResRequest) (*empty.Empty, error)
	GetResponse(context.Context, *GetResRequest) (*ResRequest, error)
	GetHostSize(context.Context, *HostSizeRequest) (*HostSizeReply, error)
}

func RegisterActivityServer(s *grpc.Server, srv ActivityServer) {
	s.RegisterService(&_Activity_serviceDesc, srv)
}

func _Activity_StoreRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServer).StoreRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/activitypb.Activity/StoreRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServer).StoreRequest(ctx, req.(*ReqRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Activity_GetRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServer).GetRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/activitypb.Activity/GetRequests",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServer).GetRequests(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Activity_UpdateRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServer).UpdateRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/activitypb.Activity/UpdateRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServer).UpdateRequest(ctx, req.(*ReqRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Activity_StoreResponse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServer).StoreResponse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/activitypb.Activity/StoreResponse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServer).StoreResponse(ctx, req.(*ResRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Activity_GetResponse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServer).GetResponse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/activitypb.Activity/GetResponse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServer).GetResponse(ctx, req.(*GetResRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Activity_GetHostSize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostSizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServer).GetHostSize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/activitypb.Activity/GetHostSize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServer).GetHostSize(ctx, req.(*HostSizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Activity_serviceDesc = grpc.ServiceDesc{
	ServiceName: "activitypb.Activity",
	HandlerType: (*ActivityServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StoreRequest",
			Handler:    _Activity_StoreRequest_Handler,
		},
		{
			MethodName: "GetRequests",
			Handler:    _Activity_GetRequests_Handler,
		},
		{
			MethodName: "UpdateRequest",
			Handler:    _Activity_UpdateRequest_Handler,
		},
		{
			MethodName: "StoreResponse",
			Handler:    _Activity_StoreResponse_Handler,
		},
		{
			MethodName: "GetResponse",
			Handler:    _Activity_GetResponse_Handler,
		},
		{
			MethodName: "GetHostSize",
			Handler:    _Activity_GetHostSize_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "activity.proto",
}

func init() { proto.RegisterFile("activity.proto", fileDescriptor_activity_569024038f4898c5) }

var fileDescriptor_activity_569024038f4898c5 = []byte{
	// 440 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xd1, 0x6e, 0xd3, 0x30,
	0x14, 0xad, 0x49, 0x3b, 0xda, 0xdb, 0x16, 0x26, 0x6b, 0xaa, 0xb2, 0x6c, 0x12, 0x91, 0x11, 0x52,
	0x9e, 0x32, 0xa9, 0xc0, 0x2b, 0xd2, 0x26, 0x8d, 0xc1, 0xab, 0x07, 0x2f, 0xbc, 0x25, 0xcb, 0x65,
	0x0b, 0x4a, 0xb0, 0x1b, 0xbb, 0x88, 0xec, 0x4b, 0xf8, 0x00, 0x3e, 0x14, 0xc5, 0x71, 0x9a, 0x28,
	0xcd, 0x98, 0xf6, 0x76, 0xaf, 0x7d, 0x7c, 0xee, 0x39, 0xe7, 0x26, 0xf0, 0x22, 0xba, 0xd1, 0xe9,
	0xaf, 0x54, 0x97, 0xa1, 0x2c, 0x84, 0x16, 0x14, 0x9a, 0x5e, 0xc6, 0xde, 0xc9, 0xad, 0x10, 0xb7,
	0x19, 0x9e, 0x99, 0x9b, 0x78, 0xfb, 0xfd, 0x0c, 0x73, 0xd9, 0x00, 0xbd, 0x57, 0xfd, 0x4b, 0x9d,
	0xe6, 0xa8, 0x74, 0x94, 0xcb, 0x1a, 0xc0, 0x7e, 0x00, 0x70, 0xdc, 0x70, 0xdc, 0x6c, 0x51, 0x69,
	0x7a, 0x04, 0x93, 0x02, 0x37, 0x9f, 0x13, 0x97, 0xf8, 0x24, 0x98, 0xf0, 0xba, 0xa1, 0x87, 0xe0,
	0x6c, 0x8b, 0xcc, 0x7d, 0xe6, 0x93, 0x60, 0xc6, 0xab, 0x92, 0xae, 0xe0, 0xe0, 0x0e, 0xa3, 0x04,
	0x0b, 0xd7, 0xf1, 0x49, 0xb0, 0xe0, 0xb6, 0xa3, 0xa7, 0x30, 0xbb, 0x11, 0xb9, 0xcc, 0x50, 0x63,
	0xe2, 0x8e, 0x7d, 0x12, 0x4c, 0x79, 0x7b, 0xc0, 0x7c, 0x98, 0x9a, 0x59, 0x32, 0x2b, 0x87, 0x27,
	0xb1, 0x8f, 0x70, 0x78, 0x85, 0xda, 0xaa, 0x51, 0x35, 0x72, 0x0d, 0xd3, 0xc2, 0x1e, 0xb8, 0xc4,
	0x77, 0x82, 0xf9, 0x7a, 0x15, 0xb6, 0xf6, 0xc3, 0x56, 0x3d, 0xdf, 0xe1, 0xd8, 0x1f, 0x52, 0xd9,
	0x52, 0x8d, 0x2d, 0x0a, 0xe3, 0x3b, 0xa1, 0xb4, 0x99, 0x35, 0xe3, 0xa6, 0x1e, 0x30, 0xe5, 0x55,
	0x83, 0x94, 0x14, 0x3f, 0x15, 0x5a, 0x5b, 0xbb, 0xbe, 0x62, 0x88, 0x45, 0x52, 0x1a, 0x4f, 0x0b,
	0x6e, 0x6a, 0xfa, 0x0e, 0x9e, 0xe3, 0x6f, 0x99, 0x16, 0xa8, 0xdc, 0x89, 0x4f, 0x82, 0xf9, 0xda,
	0x0b, 0xeb, 0xb4, 0xc3, 0x26, 0xed, 0xf0, 0x4b, 0x93, 0x36, 0x6f, 0xa0, 0xec, 0x3d, 0x2c, 0x8d,
	0xc5, 0xa7, 0x89, 0x63, 0x6f, 0xe0, 0xe5, 0x27, 0xa1, 0xf4, 0x75, 0x7a, 0x8f, 0xff, 0x79, 0xc8,
	0x5e, 0xc3, 0xb2, 0x85, 0x55, 0xe9, 0x51, 0x18, 0xab, 0xf4, 0x1e, 0x0d, 0xc8, 0xe1, 0xa6, 0x5e,
	0xff, 0x75, 0x60, 0x7a, 0x6e, 0x13, 0xa4, 0x1f, 0x60, 0x71, 0xad, 0x45, 0xb1, 0x63, 0x7d, 0x20,
	0x5c, 0xef, 0x68, 0xef, 0x5c, 0x66, 0x25, 0x1b, 0xd1, 0x4b, 0x98, 0x77, 0x56, 0x46, 0x57, 0x7b,
	0x19, 0x5c, 0x56, 0x9f, 0xa3, 0x77, 0xda, 0x7d, 0xde, 0xdf, 0x31, 0x1b, 0xd1, 0x73, 0x58, 0x7e,
	0x95, 0x49, 0xa4, 0x1f, 0xd5, 0xf1, 0xc0, 0x80, 0x9a, 0xc2, 0x3a, 0xb1, 0x4b, 0xeb, 0x51, 0xa8,
	0xc7, 0x29, 0x2e, 0xac, 0x19, 0x4b, 0x70, 0xbc, 0x27, 0xba, 0xc3, 0x31, 0xc8, 0xcd, 0x46, 0xf4,
	0xca, 0x70, 0x34, 0x5b, 0xa0, 0x27, 0x5d, 0x60, 0x6f, 0x85, 0xde, 0xf1, 0xf0, 0xa5, 0x89, 0xe4,
	0x62, 0xf1, 0xad, 0xf3, 0x9b, 0xc7, 0x07, 0x46, 0xec, 0xdb, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xce, 0x62, 0x51, 0x47, 0x0b, 0x04, 0x00, 0x00,
}
