apiVersion: v1
kind: Service
metadata:
  name: proxy-service
spec:
  selector:
    app: proxy
  ports:
  - port: 80
    name: http
  - port: 443
    name: https
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: proxy-deployment
  labels:
    app: proxy
spec:
  selector:
    matchLabels:
      app: proxy
  replicas: 3
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
      - name: proxy
        image: aistom/myproxy
        args: ["--grpc-port", "activity-service:3000"]
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https


